export const DEPARTMENTS = [
    'Ban điều hành',
    // --- Khối Phòng/Ban chức năng ---
    'Phòng Điều hành mạng',
    'Phòng Chính sách kinh doanh',
    'Phòng Nghiên cứu phát triển',
    'Phòng Kế hoạch đầu tư',
    'Phòng Tổ chức lao động',
    'Phòng Tài chính kế toán',
    'Phòng Hành chính tổng hợp',
    'Ban Kiểm soát nội bộ',

    // --- Khối các Đài/Trung tâm đặc thù ---
    'Đài Thông tin vệ tinh mặt đất Inmarsat Hải Phòng (HPLES)',
    'Đài Thông tin vệ tinh Cospas-Sarsat Việt Nam (VNLUT/MCC)',
    'Đài Thông tin Nhận dạng và truy theo tầm xa (LRIT)',
    'Đài Trung tâm Xử lý thông tin Hàng hải Hà Nội',
    'Trung tâm Viễn thông – Công nghệ thông tin',
    'Trung tâm Dịch vụ Khách hàng',

    // --- Khối các Đài TTDH (Thông tin duyên hải) ---
    'Đài TTDH Móng Cái',
    'Đài TTDH Cửa Ông',
    'Đài TTDH Hòn Gai',
    'Đài TTDH Hải Phòng',
    'Đài TTDH Bạch Long Vĩ',
    'Đài TTDH Thanh Hóa',
    'Đài TTDH Bến Thủy',
    'Đài TTDH Hòn La',
    'Đài TTDH Cửa Việt',
    'Đài TTDH Huế',
    'Đài TTDH Đà Nẵng',
    'Đài TTDH Dung Quất',
    'Đài TTDH Lý Sơn',
    'Đài TTDH Quy Nhơn',
    'Đài TTDH Phú Yên',
    'Đài TTDH Nha Trang',
    'Đài TTDH Cam Ranh',
    'Đài TTDH Phan Rang',
    'Đài TTDH Phan Thiết',
    'Đài TTDH Vũng Tàu',
    'Đài TTDH Hồ Chí Minh',
    'Đài TTDH Bạc Liêu',
    'Đài TTDH Cần Thơ',
    'Đài TTDH Côn Đảo',
    'Đài TTDH Cà Mau',
    'Đài TTDH Kiên Giang',
    'Đài TTDH Hà Tiên',
    'Đài TTDH Thổ Chu',
    'Đài TTDH Phú Quốc'
];